version: "3.3"

services:
  nextjs:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /.:/usr/src/app
      - /usr/src/app/.next
      - /usr/src/app/node_modules
    env_file:
      - .env